/**
 * GENERATED by scripts/idl/gen-idl-from-sdk.ts from @satrush/client@0.1.15 — do not edit.
 *
 * Decoded shapes of every account, event and helper type in satrush.json, as
 * the anchor coders produce them: snake_case fields, u64/i64/u128 → BN,
 * smaller ints → number, pubkey → PublicKey, option<T> → T | null, byte arrays
 * → number[], enums → single-key variant objects.
 */
import type { PublicKey } from "@solana/web3.js";
import type { BN } from "./idl.js";

export type AutomationStrategy =
  | { Static: Record<string, never> }
  | { Random: Record<string, never> }
  | { Discretionary: Record<string, never> };

export type EpochState =
  | { Open: Record<string, never> }
  | { Settling: Record<string, never> }
  | { Settled: Record<string, never> }
  | { Complete: Record<string, never> }
  | { Sealed: Record<string, never> };

export type OneBtcState =
  | { Open: Record<string, never> }
  | { Settled: Record<string, never> }
  | { Complete: Record<string, never> }
  | { Sealed: Record<string, never> };

export type RoundState =
  | { Active: Record<string, never> }
  | { Revealed: Record<string, never> }
  | { Settled: Record<string, never> }
  | { Finished: Record<string, never> };

export interface Affiliate {
  version: number;
  bump: number;
  authority: PublicKey;
  tag: number[];
  rate_bps: number;
  point_amount: BN;
  reserved: number[];
}

export interface AffiliateTag {
  version: number;
  bump: number;
  authority: PublicKey;
  reserved: number[];
}

export interface Board {
  version: number;
  bump: number;
  round_id: number;
  round_duration: number;
  start_slot: BN;
  end_slot: BN;
  strike_pending_usd_amount: BN;
  strike_usd_amount: BN;
  strike_btc_amount: BN;
  strike_last_trigger_round_id: number;
  strike_reserve_usd_amount: BN;
  strike_reserve_btc_amount: BN;
  rotor_arm_counter: BN;
  strike_token_amount: BN;
  strike_reserve_token_amount: BN;
  reserved: number[];
}

export interface EpochDrawTriggered {
  iteration_id: number;
  total_tickets: BN;
  pool_usd: BN;
  pool_btc: BN;
  pool_token: BN;
}

export interface EpochRewardDistributed {
  iteration_id: number;
  winner: PublicKey;
  rank: number;
  usd_amount: BN;
  btc_amount: BN;
  btc_shares: BN;
  token_amount: BN;
  token_shares: BN;
}

export interface EpochTicketsBought {
  authority: PublicKey;
  iteration_id: number;
  page_index: number;
  tickets_amount: BN;
}

export interface EpochVault {
  version: number;
  bump: number;
  iteration_id: number;
  last_trigger_slot: BN;
  pending_usd_amount: BN;
  pool_usd_amount: BN;
  pool_btc_amount: BN;
  reserved_usd_amount: BN;
  reserved_btc_amount: BN;
  rotor_arm_counter: BN;
  pool_token_amount: BN;
  reserved_token_amount: BN;
  reserved: number[];
}

export interface EpochVaultEntry {
  version: number;
  bump: number;
  iteration_id: number;
  authority: PublicKey;
  page_index: number;
  tickets: BN;
  reserved: number[];
}

export interface EpochVaultIteration {
  version: number;
  bump: number;
  iteration_id: number;
  state: EpochState;
  total_tickets: BN;
  participants_count: number;
  page_count: number;
  current_page_index: number;
  current_page_entry_count: number;
  entropy: number[];
  claimable_usd: BN;
  claimable_btc: BN;
  total_tickets_remaining: BN;
  current_winning_ticket: BN;
  sealed_pages_count: number;
  winners_selected: number;
  winners_distributed: number;
  winners: Winner[];
  rotor_arm_counter: BN;
  claimable_token: BN;
  reserved: number[];
}

export interface EpochVaultPage {
  version: number;
  bump: number;
  iteration_id: number;
  page_index: number;
  total_tickets: BN;
  cumulative_base: BN;
  sealed: boolean;
  entry_count: number;
  entries: PageEntry[];
  reserved: number[];
}

export interface EpochWinnerSelected {
  iteration_id: number;
  winner: PublicKey;
  rank: number;
  page_index: number;
  winning_ticket: BN;
  won_usd_amount: BN;
  won_btc_amount: BN;
  won_token_amount: BN;
  entropy: number[];
}

export interface GrubstakeAirdrop {
  version: number;
  authority: PublicKey;
  usd_amount: BN;
  expiration_timestamp: BN;
  reserved: number[];
}

export interface Miner {
  version: number;
  bump: number;
  authority: PublicKey;
  unclaimed_usd_amount: BN;
  unclaimed_btc_shares: BN;
  hashrate_amount: BN;
  current_streak_count: number;
  last_mined_round_id: number;
  unclaimed_hashrate: BN;
  grubstake_usd_amount: BN;
  grubstake_expiration_timestamp: BN;
  affiliate: PublicKey;
  unclaimed_token_shares: BN;
  reserved: number[];
}

export interface OneBtcDrawSettled {
  iteration_id: number;
  total_tickets: BN;
  winning_ticket_id: BN;
  entropy: number[];
}

export interface OneBtcTicketsBought {
  authority: PublicKey;
  iteration_id: number;
  start_ticket_id: BN;
  tickets_count: BN;
}

export interface OneBtcVault {
  version: number;
  bump: number;
  iteration_id: number;
  pending_usd_amount: BN;
  btc_amount: BN;
  reserved_btc_amount: BN;
  last_trigger_slot: BN;
  reserved: number[];
}

export interface OneBtcVaultEntry {
  version: number;
  iteration_id: number;
  authority: PublicKey;
  start_ticket_id: BN;
  tickets_count: BN;
  reserved: number[];
}

export interface OneBtcVaultIteration {
  version: number;
  bump: number;
  iteration_id: number;
  state: OneBtcState;
  total_tickets: BN;
  entropy: number[];
  winning_ticket: BN;
  prize_btc: BN;
  rotor_arm_counter: BN;
  reserved: number[];
}

export interface PageEntry {
  authority: PublicKey;
  tickets: BN;
}

export interface PublicAutomation {
  version: number;
  bump: number;
  authority: PublicKey;
  strategy: AutomationStrategy;
  selection_mask: number;
  reload: boolean;
  per_round_usd_amount: BN;
  remaining_usd_amount: BN;
  total_spent_usd_amount: BN;
  is_grubstake_funded: boolean;
  reserved: number[];
}

export interface PublicDeployCreated {
  authority: PublicKey;
  round_id: number;
  deployed_usd_amount: BN;
  total_stake_usd_amount: BN;
  selection_mask: number;
  is_automation: boolean;
  reload: boolean;
  is_grubstake_funded: boolean;
}

export interface PublicDeploySettled {
  authority: PublicKey;
  round_id: number;
  winning_stake: BN;
  won_usd_amount: BN;
  won_shares_amount: BN;
  hashrate_earned: BN;
  unclaimed_hashrate_earned: BN;
  is_automation: boolean;
  reload: boolean;
  is_grubstake_funded: boolean;
  affiliate_points_earned: BN;
  won_token_amount: BN;
  won_token_shares: BN;
}

export interface PublicDeployment {
  version: number;
  bump: number;
  authority: PublicKey;
  round_id: number;
  deployed_usd_amount: BN;
  total_stake_usd_amount: BN;
  selection_mask: number;
  streak_multiplier: number;
  automation: PublicKey | null;
  is_grubstake_funded: boolean;
  affiliate_points_usd_amount: BN;
  reserved: number[];
}

export interface Round {
  version: number;
  bump: number;
  id: number;
  state: RoundState;
  blockhash_entropy: number[];
  winning_tile: number | null;
  deployed_pending_usd_amount: BN;
  deployed_usd_amount: BN;
  deployed_btc_amount: BN;
  deployed_usd_on_winning_tile_amount: BN;
  miners_count: number;
  revealed_miners_count: number;
  winners_count: number;
  settled_miners_count: number;
  strike_bonus_usd: BN;
  strike_bonus_btc: BN;
  public_tile_stakes: TileStake[];
  minted_token_amount: BN;
  strike_bonus_token: BN;
  reserved_entropy: number[];
  settled_at_slot: BN;
  pending_epoch_fee_usd_amount: BN;
  pending_one_btc_fee_usd_amount: BN;
  pending_protocol_fee_usd_amount: BN;
  is_hashrate_boosted: boolean;
  pending_affiliate_fee_usd_amount: BN;
  pending_buybacks_fee_usd_amount: BN;
  deployed_gross_usd_amount: BN;
  reserved: number[];
}

export interface RoundRevealed {
  round_id: number;
  winning_tile: number;
  is_strike_triggered: boolean;
  strike_bonus_usd: BN;
  strike_bonus_btc: BN;
  strike_epoch_usd: BN;
  strike_epoch_btc: BN;
  strike_reserve_usd: BN;
  strike_reserve_btc: BN;
  strike_seed_from_reserve_usd: BN;
  strike_seed_from_reserve_btc: BN;
  epoch_fee_usd_amount: BN;
  one_btc_fee_usd_amount: BN;
  protocol_fee_usd_amount: BN;
  affiliate_fee_usd_amount: BN;
  buybacks_fee_usd_amount: BN;
  minted_token_amount: BN;
  strike_token_amount: BN;
  strike_bonus_token: BN;
  strike_epoch_token: BN;
  strike_reserve_token: BN;
  strike_seed_from_reserve_token: BN;
}

export interface RoundStakeSwapped {
  round_id: number;
  deployed_usd_amount: BN;
  deployed_btc_amount: BN;
}

export interface SatrushConfig {
  version: number;
  bump: number;
  owner_authority: PublicKey;
  admin_authority: PublicKey;
  game_authority: PublicKey;
  fee_recipient: PublicKey;
  usd_mint: PublicKey;
  btc_mint: PublicKey;
  strike_fee_bps: number;
  epoch_fee_bps: number;
  one_btc_fee_bps: number;
  sats_vault_round_fee_bps: number;
  vault_exit_fee_bps: number;
  protocol_fee_bps: number;
  unclaimed_hashrate_bps: number;
  min_deploy_usd_amount: BN;
  epoch_vault_iteration_duration: BN;
  deployment_settle_grace_duration: BN;
  strike_trigger_modulus: number;
  buybacks_fee_bps: number;
  token_mint: PublicKey;
  reserved: number[];
}

export interface SatsClaimed {
  authority: PublicKey;
  claimed_shares: BN;
  btc_received: BN;
  claimed_hashrate: BN;
  claimed_token_shares: BN;
  tokens_received: BN;
}

export interface SatsVault {
  version: number;
  bump: number;
  btc_amount: BN;
  btc_shares: BN;
  leftovers: BN;
  reserved: number[];
}

export interface TileStake {
  stake: BN;
  deploy_count: number;
}

export interface TokenClaimed {
  authority: PublicKey;
  claimed_shares: BN;
  tokens_received: BN;
  claimed_sats_shares: BN;
  btc_received: BN;
  claimed_hashrate: BN;
}

export interface TokenVault {
  version: number;
  bump: number;
  token_amount: BN;
  token_shares: BN;
  leftovers: BN;
  reserved: number[];
}

export interface Treasury {
  version: number;
  bump: number;
  protocol_fees_usd_amount: BN;
  protocol_fees_btc_amount: BN;
  grubstake_total_usd_amount: BN;
  grubstake_reserved_usd_amount: BN;
  grubstake_affiliate_reserved_usd_amount: BN;
  token_buybacks_usd_amount: BN;
  staking_buybacks_usd_amount: BN;
  reserved: number[];
}

export interface Winner {
  authority: PublicKey;
  page_index: number;
  tickets: BN;
  distributed: boolean;
}

